name: example
description: A sample command-line application.
version: 0.0.0
publish_to: none
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/packagex.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  packagex:
    path: ../

packagex: 
  command: ""
  
msix_config:
  display_name: example
  publisher_display_name: Azkadev Packagex
  identity_name: org.azkadev.example
  msix_version: 0.0.0.0
  logo_path: example/bin/example.dart
  capabilities: "internetClient, location, microphone, webcam"