name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '^3.6.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8' 
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  msix: '^3.16.8'
  packagex:
    path: ../
flutter:
  uses-material-design: true
packagex:
  name: 'example'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_commands:
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  uploads:
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@general_release_action_publisher'
          message_thread_id: ''
        - chat_id: '-1002282230821'
          message_thread_id: ''
        - chat_id: '7116956141'
          message_thread_id: ''
  packages:
    - dart_target: 'example'
      flutter_target: 'example'
      dart_name: 'example'
      flutter_name: 'example'
      output_name: 'example'
msix_config:
  display_name: 'example'
  install_certificate: false
