name: 'example'
description: 'A sample command-line application.'
version: '0.0.0'
publish_to: 'none'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  packagex: 
    path: '../'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
  msix: '^3.16.7'
packagex: 
  name: 'example'
  dart_target: 'example'
  flutter_target: 'main'
  dart_name: 'example'
  flutter_name: 'example'
  is_without_platform_name: true
  flutter_commands: 
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  project_id: 'azkadev.packagex'
  github_username: 'azkadev'
  github_is_org: false
msix_config: 
  display_name: 'example'
  install_certificate: false
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
