name: packagex
description: A library for package dart or flutter to specific platform.
version: 0.0.7
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  packagex: packagex
dependencies:
  archive: ^3.3.5
  galaxeus_lib: ^0.0.34
  path: ^1.8.2
