name: packagex
description: A library for package dart or flutter to specific platform.
version: 0.0.51
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/packagex.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  msix: ^3.16.7
  test: ^1.24.2

executables:
  packagex: packagex
  
dependencies:
  # archive: ^3.4.10
  collection: ^1.18.0
  general_lib: ^0.0.37
  github: ^9.24.0
  http: ^1.2.1
  mason_logger: ^0.2.15
  mime: ^1.0.5
  path: ^1.9.0
  universal_io: ^2.2.2
  yaml: ^3.1.2
  yaml_writer: '^2.0.0'

packagex:
  
  name: packagex
  dart_target: packagex
  flutter_target: main
  dart_name: packagex
  flutter_name: packagex
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  project_id: "azkadev.packagex"
  github_username: azkadev
  
msix_config: 
  display_name: packagex
  install_certificate: false
   